scan:
  inventory-open: true
  player-join: true
  player-quit: true
  player-death: true
  entity-pickup-item: true
  chunk-load: true
# Config the max container-in-container recursive scan depth
recursive-scan-depth: 3
save:
  # The items will keep in the memory if below this value and IV will randomly flush them to database to reduce the db load
  lazy-threshold: 512
  # Save only 1/X of items to the database per save to dynamically scale to alleviate save pressure
  batch-partition-divide-by: 3
  # If the number of items is less than this value after dividing, raise it to this value.
  min-batch-size: 1000
database:
  mysql: false
  host: localhost
  port: 3306
  database: itemvoid
  user: root
  password: passwd
  prefix: "itemvoid_"
  usessl: false
  properties:
    connectionTimeout: 60000
    idleTimeout: 10000
    maxLifetime: 1800000
    maximumPoolSize: 4
    minimumIdle: 4
    cachePrepStmts: true
    prepStmtCacheSize: 250
    prepStmtCacheSqlLimit: 2048
    useUnicode: true
    characterEncoding: utf8
    allowPublicKeyRetrieval: true
    keepaliveTime: 60000