name: ItemVoid
version: '${project.version}'
main: com.ghostchu.plugins.itemvoid.ItemVoid
api-version: '1.20'
libraries:
  - com.h2database:h2:2.1.214
depend:
  - NBTAPI
commands:
  itemvoid:
    description: main command